Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-06, with the labels that each got.

#45 add selinux module check
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#46 Update modcheck path
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#47 Add first guest-oslogin PS
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#48 Update image for cpp builds
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#49 Temporarily remove iamsubratp from reviewers
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS

#50 Add initial PS for guest-configs repo.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S
