Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-08, with the labels that each got.

#60 Add oncall to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#59 Bump prow to v20190827-256e5bbca
  prow/bump.sh
  prow/cluster.yaml
  prow/config.yaml
  prow/grandmatriarch.yaml
Labels: approved, lgtm, size/L

#61 Revert "Update prow to v20190830-56bd52b0e."
  prow/cluster.yaml
  prow/config.yaml
  prow/grandmatriarch.yaml
Labels: approved, lgtm, size/S
