Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-04, with the labels that each got.

#7 add gcp-guest cluster into oss-prow build clusters
  prow/cluster.yaml
  prow/config.yaml
Labels: approved, size/M

#10 bump oss-prow, add build-cluster to deck, report on github
  prow/cluster.yaml
Labels: approved, size/S

#11 Add plugins for osconfig repository
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#12 split oss-prow job configs into subdirs
  prow/cluster.yaml
  prow/config.yaml
  prow/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/kunit-review.googlesource.com/linux/kunit-linux-config.yaml
Labels: approved, size/L

#13 GCP-guest updates
  prow/cluster.yaml
  prow/config.yaml
  prow/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#14 bump oss-prow to v20190430-6a7dd776a
  prow/cluster.yaml
  prow/config.yaml
Labels: approved, do-not-merge/hold, lgtm, size/S

#16 add rbac for tide
  prow/cluster.yaml
Labels: approved, lgtm, size/M
