Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-05, with the labels that each got.

#17 add --job-config-path for hook
  prow/cluster.yaml
Labels: approved, lgtm, size/XS

#15 touch the oss-test-infra config
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#18 fix wrong indentation for the gcp-guest config
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#19 Use liam's gobuild container image
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#21 decorate presubmit jobs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#23 add explicit command/args to gcp-guest jobs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#24 add tide/hook urls to deck
  prow/cluster.yaml
Labels: approved, lgtm, size/S

#25 update command paths
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#26 fix oauth secret name
  prow/cluster.yaml
Labels: approved, lgtm, size/XS

#27 GCP-guest: use non-wrapper versions when decorated
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#28 gcp-guest: add unittests presubmit
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#29 Add test post submit job to be triggered on osconfig repo
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#30 Add cluster for post submit job
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, size/XS

#31 fix indent for osconfig-agent-build
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#34 Update gcp-guest containers
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#35 correct path for gcp-guest agent build
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm

#36 Enable spyglass for oss-prow
  prow/config.yaml
Labels: approved, lgtm, size/S

#32 make presubmit takes in job-config-path as well
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#38 use checkconfig image for presubmit
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#39 go presubmits for guest-agent repo
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#41 Fix deck rbac, bump prow to latest
  prow/cluster.yaml
  prow/config.yaml
Labels: approved, lgtm, size/S

#33 remove debug cluster inspection jobs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#42 Enable tide for more guest repos
  prow/config.yaml
Labels: approved, lgtm, size/XS

#43 enable review_acts_as_lgtm for this repo
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#37 [gcp-guest] Fix agent build postsubmit job
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#44 rename daisy-builder; add env
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S
