Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-11, with the labels that each got.

#156 add extra_refs and annotations to packagebuild
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#133 packagebuild for guest-agent and guest-oslogin
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#158 Add Prow Job to push TestGrid Configs to k8s-testgrid
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#162 update sinker and deck rbac
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/S

#161 Addition of TestGrid dashboards
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#166 Add git bot credentials for guest-test-infra
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#167 Update build workflow parameter to newer style builds
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#168 apiproxy: add build and presubmit jobs to prow
  prow/prowjobs/GoogleCloudPlatform/api-proxy/api-proxy.yaml
Labels: approved, lgtm, ok-to-test, size/S

#169 Import guest build tools for post-submit jobs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S
