Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-12, with the labels that each got.

#176 Authorize rerun using GoogleCloudPlatform org
  prow/config.yaml
Labels: approved, lgtm, size/XS

#186 Update Robot Email Address
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, kind/oncall-hotlist, lgtm, size/XS

#185 Add TestGrid Presubmit Test
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#190 TestGrid Dashboard Fix
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  testgrid/config.yaml
Labels: approved, kind/oncall-hotlist, lgtm, size/M

#194 setup esp-v2 oss basic prowjob
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, ok-to-test, size/S
