Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2019-10, with the labels that each got.

#109 correct bump.sh paths
  prow/bump.sh
Labels: approved, lgtm, size/XS

#111 Add "preset-service-account" preset
  prow/config.yaml
Labels: approved, lgtm, size/S

#110 bump prow to v20191003-b778d6be9
  prow/cluster/cluster.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#112 gcp guest add jobs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#113 bump prow
  prow/cluster/cluster.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#114 Add a periodic job to autobump Prow.
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#116 Update prow to v20191009-0492f1d6e
  prow/cluster/cluster.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#117 Correct gcloud-in-go image
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#118 Fake change to trigger deploy
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#121 Bump autobump.
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#120 Only bump prow images
  prow/bump.sh
Labels: approved, lgtm, size/XS

#122 Fix autobump version typo.
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#87 Testgrid: Add Automatic Image Deployment
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
Labels: approved, lgtm, size/S

#124 Enable override plugin in oss-test-infra
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#125 Fix plugin config
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#130 Enable lifecycle plugin
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#131 Fix prow config validation.
  prow/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#136 Migrate to default_decoration_configs
  go.mod
  go.sum
  prow/config.yaml
Labels: approved, lgtm, size/L

#100 Enable OSS rerun for all googlers
  prow/cluster/cluster.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#144 Revert "Merge pull request #143 from google-oss-robot/autobump"
  prow/cluster/cluster.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm

#149 Move push-testgrid-images to trusted cluster
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
Labels: approved, lgtm, size/M

#150 Set --cookie-secret for deck
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#154 add annotations to osconfig-presubmit-build
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS
