Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2020-05, with the labels that each got.

#355 add diskexpand, configs repos
  prow/config.yaml
  prow/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#363 add compute-image-tools presubmits
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#368 [ESPv2] Update prow images for Envoy update
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#369 [ESPv2] Update coverage images
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/XS

#365 Add required --github-token-path to hook/tide.
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#367 add new presubmit, move c-i-t jobs to second file
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XL

#371 [ESPv2] Revert back serverless e2e images
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#372 Remove @rofuentes from reviewers list
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS
