Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2020-06, with the labels that each got.

#375 Enable trigger and add a job for en-server.
  prow/config.yaml
  prow/plugins.yaml
  prow/prowjobs/google/exposure-notifications-server/OWNERS
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/M

#376 Switch en-server from internal Prow to OSS Prow.
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/M

#378 Make en-server presubmit report.
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/XS

#379 Allow en-server repo admins to override old job.
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#381 More resources for exposure notification
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/XS

#377 Update crier flags.
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/S

#382 Update oss-test-infra OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#383 test all of daisy/
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#384 Added missing checks/tests/builds for cli_tools
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/L

#385 disable tide for compute-image-tools
  prow/config.yaml
Labels: approved, lgtm, size/XS

#380 Move oss-prow configs one level below
  README.md
  go.mod
  prow/bump.sh
  prow/oss/Makefile
  prow/oss/Makefile.gcloud.mk
  prow/oss/README.md
  prow/oss/cluster/build/grandmatriarch_test-pods.yaml
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/config.yaml
  prow/oss/create-build-cluster.sh
  prow/oss/pj-on-kind.sh
  prow/oss/plugins.yaml
  prow/oss/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml
  prow/oss/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/temp_test.go
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/XXL

#388 Clean up duplicated prow configs
  prow/Makefile
  prow/Makefile.gcloud.mk
  prow/README.md
  prow/cluster/build/grandmatriarch_test-pods.yaml
  prow/cluster/cluster.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/oss/create-build-cluster.sh
  prow/oss/pj-on-kind.sh
  prow/pj-on-kind.sh
  prow/plugins.yaml
  prow/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml
  prow/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml
  prow/temp_test.go
Labels: approved, lgtm, size/XXL

#389 Revert "Bump prow from v20200608-16190316cf to v20200609-2d17640dc1"
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, kind/oncall-hotlist, lgtm, size/M

#392 [ESPv2] Reduce periodic test triggering
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#394 postsubmit only for master branch
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#395 Add postsubmit job updating knative prow deployment
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#397 Update --kubeconfig to use new key.
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#399 Add a canary job testing build cluster for apollo server repo
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/S

#398 exposure-notification jobs use build cluster
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/XS

#401 Delete apollo server canary job
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/S

#403 Apollo Server test: add a canary job for testing GCS access token
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/M

#402 Add configurations for exposure notifications verification server
  prow/prowjobs/google/exposure-notifications-verification-server/OWNERS
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/S

#404 Apollo server: move canary to prod
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/S

#405 Add Exposure Notification Verification Server to plugins, repos
  prow/oss/config.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#410 respect github status in reviewer assignment
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#408 Protect knative prow cluster from being used by any job
  prow/knative/OWNERS
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/M

#407 Add knative prow core and plugins config here
  prow/knative/README.md
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/L

#412 Knative prow stop updating core and plugins. Mirror from https://github.com/knative/test-infra/pull/2255
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/XS

#411 mirror en-server config to en-verification-server
  prow/oss/plugins.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/S

#413 Update kubeconfig to 'oss-config-20200630' to include knative-prow-trusted cluster.
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#409 Updateconfig plugin updates knative prow configs from oss-test-infra prow
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S

#415 Add performance test job for exposure notification server
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#414 Delete unused comment in knative prow core config file
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#416 Mount kubeconfig secret for hook
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#417 Noop update on knative core config
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#406 Add auto bump job for knative prow configs
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#418 Revert addition of Knative Prow autobump job.
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M
