Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2020-12, with the labels that each got.

#629 Remove el6 from builds/presubmits.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#630 Enable cherrypicker plugin for Knative orgs
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/S

#631 Add testgrid alerts for important prow maintenance jobs
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#632 Prow alert emails send to oncall
  prow/knative/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
  prow/oss/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
Labels: approved, lgtm, size/XS

#635 Remove resultstore service account and jobs.
  prow/oss/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#640 Add a heartbeat job for oss prow
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#643 [ESPv2] Update GKE version
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#639 Prow alert when images are stale for 14 days
  prow/knative/cluster/monitoring/mixins/lib/config.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/stale_alerts.libsonnet
  prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/stale_alerts.libsonnet
Labels: approved, lgtm, size/M

#644 Upgrade golang to 1.15
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M
