Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2020-11, with the labels that each got.

#585 Fixing prow autobump by using prow controller manager as reference
  prow/knative/cluster/400-crier.yaml
  prow/knative/cluster/400-deck.yaml
  prow/knative/cluster/400-ghproxy.yaml
  prow/knative/cluster/400-hook.yaml
  prow/knative/cluster/400-horologium.yaml
  prow/knative/cluster/400-prow-controller-manager.yaml
  prow/knative/cluster/400-sinker.yaml
  prow/knative/cluster/400-tide.yaml
  prow/knative/cluster/500-needs-rebase.yaml
  prow/knative/cluster/500-status-reconciler.yaml
  prow/knative/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#576 Add torvalds/master branch to Prow config
  prow/prowjobs/kunit-review.googlesource.com/linux/kunit-linux-config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#575 Add OWNERS file for KUnit GoB instance
  prow/prowjobs/kunit-review.googlesource.com/linux/OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#588 EN jobs: request high CPUS to ensure only a single job runs on the sa…
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/S

#589 Replace plank with prow-controller-manager on grafana dashboard
  prow/knative/cluster/monitoring/prow_servicemonitors.yaml
  prow/oss/cluster/monitoring/prow_servicemonitors.yaml
Labels: approved, lgtm, size/XS

#591 Knative prow begins monitoring knative-prow-robot/test-infra repo
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/M

#590 Knative prow: define the same sinker spec as oss prow
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#592 Use custom mirror of postgres image in tests
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/XS

#593 Use custom redis image too
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/XS

#595 Add exposure notification verification server e2e test to Prow.
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, ok-to-test, size/M

#597 Fix typos for verification server job and tab names.
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#598 Delete redundant controller manager config.
  prow/oss/cluster/controller-manager.yaml
Labels: approved, lgtm, size/L

#599 Update rbac for oss-prow.
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#600 Update rbac for knative-prow.
  prow/knative/cluster/301-rbac.yaml
  prow/knative/cluster/400-prow-controller-manager.yaml
Labels: approved, lgtm, size/M

#601 Fix oss autobumper job
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#602 Relax oss prow alert: only alert after 60 minutes without webhook events
  prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
Labels: approved, lgtm, size/XS

#605 Revert "Bump oss-prow from v20201106-ea76c130fa to v20201112-00537d1bb4"
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/tide.yaml
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, size/M

#604 Fix rbac for prow controller manager
  prow/oss/cluster/prow-controller-manager.yaml
Labels: approved, kind/oncall-hotlist, lgtm, size/M

#608 Revert "Bump knative-prow from v20201109-a36ed74f01 to v20201116-dbd6…
  prow/knative/cluster/400-crier.yaml
  prow/knative/cluster/400-deck.yaml
  prow/knative/cluster/400-ghproxy.yaml
  prow/knative/cluster/400-hook.yaml
  prow/knative/cluster/400-horologium.yaml
  prow/knative/cluster/400-prow-controller-manager.yaml
  prow/knative/cluster/400-sinker.yaml
  prow/knative/cluster/400-tide.yaml
  prow/knative/cluster/500-needs-rebase.yaml
  prow/knative/cluster/500-status-reconciler.yaml
  prow/knative/config.yaml
Labels: size/S

#609 Fix typo in prow controller manager
  prow/oss/cluster/prow-controller-manager.yaml
Labels: approved, lgtm, size/XS

#607 Fix knative prow contrller manager indentation, add yamllint job
  common/config/.yamllint.conf
  prow/knative/cluster/400-prow-controller-manager.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, kind/oncall-hotlist, lgtm, size/L

#616 Replace the image used by pull-lint-validator with a more up-to-date …
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#618 Fix yamllint job scanning path
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#619 Enable retitle plugin in knative repositories
  prow/knative/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#615 Enforce yamllint in presubmit gate
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#622 Fix typo in key server terraform smoke test tab.
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#603 Configure cherrypicker plugin for Knative Prow
  prow/knative/cluster/500-cherrypicker.yaml
Labels: approved, lgtm, size/M

#623 EN server: continuously running general tests
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/M

#624 Changing cluster Deployments to "apps/v1"
  prow/knative/cluster/400-crier.yaml
  prow/knative/cluster/400-deck.yaml
  prow/knative/cluster/400-hook.yaml
  prow/knative/cluster/400-horologium.yaml
  prow/knative/cluster/400-sinker.yaml
  prow/knative/cluster/400-tide.yaml
  prow/knative/cluster/build/400-boskos-deployment.yaml
  prow/knative/cluster/build/400-boskos-janitor.yaml
  prow/knative/cluster/build/400-boskos-reaper.yaml
Labels: approved, lgtm, size/M

#628 Revert "EN server: continuously running general tests"
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/M

#626 Update to newer CI images
  prow/prowjobs/google/exposure-notifications-server/OWNERS
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/OWNERS
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/M
