Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2020-04, with the labels that each got.

#334 move gce to guest-configs repo
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#335 Fix hook RBAC and CRD validation.
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#338 Fix indentation in create-build-cluster.sh
  prow/create-build-cluster.sh
Labels: approved, lgtm, size/S

#339 plugins for guest-configs
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#342 Migrate to rerun_auth_configs
  prow/config.yaml
Labels: approved, lgtm, size/XS

#340 create-build-cluster.sh works for other Prow instance as well
  prow/create-build-cluster.sh
Labels: approved, lgtm, size/S

#344 Deploy and use ghproxy for Prow components.
  prow/cluster/ghproxy.yaml
Labels: approved, lgtm, size/M

#346 Fix ghproxy deployment apiversion.
  prow/cluster/ghproxy.yaml
Labels: approved, lgtm, size/XS

#347 Fix ghproxy deployment selector.
  prow/cluster/ghproxy.yaml
Labels: approved, lgtm, size/XS

#345 Switch Prow components to use ghproxy.
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#348 Revert "Bump prow from v20200417-a6017ee5b to v20200422-8c8546d74"
  prow/cluster/cluster.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#350 Touch cluster file to trigger Prow deployment.
  prow/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#353 Revert "Bump prow from v20200417-a6017ee5b to v20200427-baaf248ed"
  prow/cluster/cluster.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/grandmatriarch_default.yaml
  prow/cluster/grandmatriarch_test-pods.yaml
  prow/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#352 [ESPv2] Better testgrid configuration
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/L
