Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2020-09, with the labels that each got.

#494 Removing deprecated `github-token-path` plank arg
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#495 En verification server: add canary e2e test job
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/M

#500 Update prow image to 20200903
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#501 Update prow image for tsan
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/XS

#497 Remove deprecated plank arg
  prow/knative/cluster/400-plank.yaml
Labels: approved, lgtm, size/XS

#502 En server: terraform smoke test continuous job
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/M

#505 En verification server: Continuously running terraform smoke test
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/M

#506 En server: email notify if prow jobs failed
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Labels: approved, lgtm, size/XS

#514 En server: add an e2e test job, update entrypoint of smoke test
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Labels: approved, lgtm, size/M

#513 Move plank and sinker into their own files
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/controller-manager.yaml
  prow/oss/cluster/plank.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/XL

#519 Move oss-prow components to their own files
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/XXL

#520 Update sinker permissions.
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/XS

#521 Bump oss-prow from v20200921-becd8c9356 to v20200925-a1858f46d6
  prow/oss/cluster/controller-manager.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/plank.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/tide.yaml
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#524 compute-image-tools: Restructured tests directory.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/M
