Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-02, with the labels that each got.

#690 Update espv2-owners
  prow/prowjobs/GoogleCloudPlatform/esp-v2/OWNERS
Labels: approved, lgtm, size/XS

#689 [ESPv2] Remove GKE version
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#691 [ESPv2] Switch back to stable releases for GKE kubekins
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#678 OSS prow monitoring: update based on all recent improments from k8s prow monitoring stack
  prow/oss/cluster/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
  prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
  prow/oss/cluster/monitoring/mixins/lib/config_util.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/stale_alerts.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/tide_alerts.libsonnet
Labels: approved, lgtm, size/L

#692 Fix prow monitoring stack
  prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
Labels: approved, lgtm, size/S

#693 Knative prow monitoring: update based on all recent improments from k8s prow monitoring stack
  prow/knative/cluster/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
  prow/knative/cluster/monitoring/mixins/lib/config.libsonnet
  prow/knative/cluster/monitoring/mixins/lib/config_util.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/boskos_alerts.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/plank_alerts.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/stale_alerts.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/tide_alerts.libsonnet
Labels: approved, lgtm, size/L

#696 Adjust prow components absent alert threshold from 5 to 10 minutes
  prow/knative/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
Labels: approved, lgtm, size/XS

#700 [ESPv2] Switch kubekins versions to GKE regular release channel
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#701 Replace old autobump job with new, configurable autobump
  prow/knative/knative-autobump-config.yaml
  prow/oss/oss-autobump-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/L

#704 Disable tide validation while we explore CODEOWNERS
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#702 Drop lgtm/approved labels for net-contour
  prow/knative/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#706 Disable blunderbuss, remove self-approve.
  prow/knative/plugins.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#707 test(kubeflow): rename KFP prowjob files to include pipelines
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#708 test(kubeflow): add tests for website , gcp-blueprints and testing
  prow/prowjobs/kubeflow/gcp-blueprints/kubeflow-gcp-blueprints.yaml
  prow/prowjobs/kubeflow/testing/kubeflow-testing.yaml
  prow/prowjobs/kubeflow/website/kubeflow-website.yaml
Labels: approved, lgtm, size/L

#710 test(kubeflow): increase timeout of kubeflow-pipelines-postsubmits.yaml to 2h
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
Labels: approved, lgtm, size/XS

#709 Use CODEOWNERS file for approvals in net-*
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/S

#711 Switch the sample and productivity repos over to CODEOWNERS
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#712 Fix oss autobump job pointing at knative autobump config
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#717 test(kubeflow): fix kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
Labels: approved, lgtm, size/XS

#714 Move the knative-sandbox org to CODEOWNERS
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M
