Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-08, with the labels that each got.

#1000 test: fix kfp periodic cleanup job by changing image.
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
Labels: approved, lgtm, size/XS

#992 oss-prow reporting build clusters statuses in GCS
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1005 Increase Sub replicas from 1 to 10.
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/XS

#1006 add gcp-guest bucket for spyglass
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1007 test(kubeflow): add run_if_changed for kubeflow-pipeline-{e2e,sample,upgrade}-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1010 add cit-periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#1011 Update testgrid unit test image to something with bazel 3.4.1 and 3.0.0
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
Labels: approved, lgtm, size/XS

#1012 Switch to testgrid variant of bazelbuild
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#1014 Use testgrid variant of gcloud-bazel
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#1013 Cleanup OWNERS files.
  OWNERS
Labels: approved, lgtm, size/XS

#1001 Terraform alert on pod crashlooping
  prow/oss/terraform/main.tf
  prow/oss/terraform/modules/alerts/main.tf
  prow/oss/terraform/modules/alerts/variables.tf
Labels: approved, lgtm, size/M

#1016 Add terraform config for a predicted-gh-rate-limit-exhaustion alert.
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/M

#1021 Terraform validation and fixes to gh rate limit exhaustion prediction query.
  prow/oss/terraform/Makefile
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/M

#1023 Fixing heartbeat job stale alert
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/S

#1026 Fix heartbeat job alert by summing values from all pods
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/XS

#1025 webhook missing alert with terraform
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/M

#1030 Fix webhook missing alert
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/XS

#1035 Add serviceaccounts.yaml file to build cluster.
  prow/oss/cluster/build/serviceaccounts.yaml
Labels: approved, lgtm, size/XS

#1038 Use presubmits SA on the testgrid presubmit
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
Labels: approved, lgtm, size/XS

#1039 Add default prowjob service account for workload identity
  prow/oss/cluster/build/serviceaccounts.yaml
Labels: approved, lgtm, size/XS

#1040 All jobs using default build cluster use WI by default
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1044 Increase hook replicas to 6 and set resource requests
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/XS

#1045 Add liveliness and readinessprobe for hook
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/S

#1019 Adding linux-review Gerrit instance for Prow
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/linux-review.googlesource.com/OWNERS
  prow/prowjobs/linux-review.googlesource.com/linux/kernel/git/torvalds/linux.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#1037 Add optional fields to avoid noise from terraform plan
  prow/oss/terraform/modules/alerts/probers.tf
Labels: approved, lgtm, size/XS

#1047 Configure tenantIDs for private prowjobs
  prow/oss/config.yaml
Labels: approved, lgtm, size/S

#1051 Create SA for running jobs in test-infra-trusted cluster
  prow/oss/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml
Labels: approved, lgtm, size/XS

#1055 Add external secret from build cluster for looker-int-test
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#1056 Add build cluster kubeconfig for looker-int-test
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#1057 Add build-looker-int-test cluster
  prow/oss/config.yaml
Labels: approved, lgtm, size/S, ok-to-test

#1052 Jobs in test-infra-trusted cluster use WI by default
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1058 add listx as approver for the repo
  OWNERS
Labels: approved, lgtm, size/XS

#949 Move branchprotector config for Knative to the core Prow config file
  prow/knative/config.yaml
Labels: approved, lgtm, size/M

#1063 Revert "Bumping oss-prow"
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/sub.yaml
  prow/oss/cluster/tide.yaml
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/M

#1073 Bumping sub with hot fix for set origin url
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/XS

#1075 Add external secret from build cluster for looker-16
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#1076 Add build cluster kubeconfig for looker-16
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#1077 Add external secret from build cluster for looker-32
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S, ok-to-test
