Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-05, with the labels that each got.

#828 Private deck accessible only to a specific team
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#826 Onboard looker org.
  prow/oss/config.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S

#830 Using looker key only
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#833 Temporarily disable monitoring ingress.
  prow/oss/cluster/monitoring/grafana_expose.yaml
Labels: approved, lgtm, size/S

#834 Update deck-private RBAC.
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#835 Make private deck HA and add readiness probes to public deck.
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/S

#836 Restrict to only helltool repo from looker org
  prow/oss/config.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#837 Configure private tide target_url for private looker repo.
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#838 only private repo in chaotoppicks repo can use private build cluster
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#839 Add back job config checker job for looker/helltool
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/S

#840 Make helltool Prow config validation only run on config changes and disable size plugin.
  prow/oss/plugins.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/XS

#841 Add GoogleCloudPlatform/k8s-cloud-provider to tide
  prow/oss/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#842 Enable Google Analytics for both OSS and Knative Prow.
  prow/knative/config.yaml
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#847 Drop chaotoppicks from oss prow
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/chaotoppicks/great-private-tools/great-private-tools.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/chaotoppicks/great-tools/great-tools.yaml
Labels: approved, lgtm, size/M

#852 Require self approval for kubeflow training operators
  prow/oss/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#851 Automated continuous deployment of oss prow
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#850 Add new prow job for elcarro-oracle-operator
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/elcarro-oracle-operator/OWNERS
  prow/prowjobs/GoogleCloudPlatform/elcarro-oracle-operator/elcarro-oracle-operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#855 Knative prow: switch grafana password to be from external secret
  prow/knative/cluster/600-kubernetes_external_secrets.yaml
  prow/knative/cluster/monitoring/secrets/grafana_secret.yaml
Labels: approved, lgtm, size/M

#854 Switch grafana password to be from external secret
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/cluster/monitoring/secrets/grafana_secret.yaml
Labels: approved, lgtm, size/S

#853 Update OWNERS file for elcarro-oracle-operator project - add kchernyshev
  prow/prowjobs/GoogleCloudPlatform/elcarro-oracle-operator/OWNERS
Labels: approved, lgtm, size/XS

#858 Add external secret from build cluster for elcarro
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S

#857 Add build cluster kubeconfig for elcarro
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#856 Update cluster name for elcarro-oracle-operator project
  prow/prowjobs/GoogleCloudPlatform/elcarro-oracle-operator/elcarro-oracle-operator.yaml
Labels: approved, lgtm, size/XS

#859 Enable workload identity for build-elcarro cluster
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#860 Project oracle-elcarro: fix bucket name
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#861 Fix oss prow onboarding bugs
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#846 Set up a periodic test job to run e2e tests against main once a day
  prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/S

#863 Increase pod unscheduled timeout to 5 minutes
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#843 Add external secret from build cluster for knative
  prow/knative/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, ok-to-test, size/S

#864 Mention autobump in oss prow README
  prow/oss/README.md
Labels: approved, lgtm, size/XS

#870 Add a prow job for updating oss prow monitoring stack
  prow/oss/monitoring-autobump-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#872 Undo #714 and use prow /lgtm and /approve
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#874 Add external secret for knative build cluster
  prow/knative/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#871 Add prow job config path on testgrid
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#877 Add external secret for knative build cluster
  prow/knative/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#878 TG config upload: stop setting file-level permission
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS
