Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-11, with the labels that each got.

#1249 GoogleCloudPlatform all switch over to use GitHub app
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/S

#1254 Stop managing hmac tokens for GoogleCloudPlatform repos
  prow/oss/config.yaml
Labels: approved, lgtm, size/M

#1253 Migrate kubeflow org to use GitHub app for authenticating
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/XS

#1257 Stop managing hmac tokens for kubeflow repos
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1233 secrets-store-csi-driver-provider-gcp: remove
  prow/oss/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/OWNERS
  prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#1248 Move oss-test-infra presubmits to in-repo config.
  .prow/OWNERS
  .prow/presubmits.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/L

#1259 Revert "Add '-temp' suffix to in-repo config presubmits to avoid conflict."
  .prow/presubmits.yaml
  prow/oss/oss-autobump-config.yaml
Labels: approved, lgtm, size/S

#1252 Separate testgrid jobs
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/GoogleCloudPlatform/testgrid/OWNERS
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/L

#1260 Make OSS Prow config validation check for unknown fields in job config.
  .prow/presubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
Labels: approved, lgtm, size/S

#1269 Fix default branch name for blueprints checkconfig canary.
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
Labels: approved, lgtm, size/XS

#1267 Update uptime probe alerts to ignore extraneous uptime_checks.
  prow/oss/terraform/main.tf
  prow/oss/terraform/modules/alerts/main.tf
  prow/oss/terraform/modules/alerts/probers.tf
  prow/oss/terraform/modules/alerts/variables.tf
Labels: approved, lgtm, size/S

#1266 Add missing clone_uri for looker checkconfig canary.
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/XS

#1258 Looker performance tests dashboards typo fix
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#1271 Boskos alerts: add missing prerequisite steps
  prow/oss/terraform/README.md
Labels: approved, lgtm, size/M

#1272 Fix blackbox probe terraform config.
  prow/oss/terraform/main.tf
  prow/oss/terraform/modules/alerts/variables.tf
Labels: approved, lgtm, size/XS

#1274 Make blueprints checkconfig presubmit include strict validation.
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
Labels: approved, lgtm, size/M

#1273 Make looker checkconfig presubmit include strict validation.
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/M

#1277 github/google org switches to use GitHub app for prow
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/XS

#1281 Use updated kubeconfig which doesn't have build-csi cluster
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/S

#1282 grpc-ecosystem uses GitHub app for prow
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/XS

#1278 Stop managing hmac tokens for google repos
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1283 Stop managing hmac tokens for grpc repos
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1285 Collect GKE workload metrics on ghapp based hook and crier
  prow/oss/cluster/monitoring/prow_podmonitors.yaml
Labels: approved, lgtm, size/M

#1286 Fix the webhook-missing alerts to only count webhooks from the relevant instance.
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/XS

#1290 Googleforgames org uses GitHub app
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
Labels: approved, lgtm, size/XS

#1288 Prow auto-deploy cron adjusts against daylight saving
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#1291 Remove all managed webhooks
  prow/oss/config.yaml
Labels: approved, lgtm, size/S

#1292 Migrate tide to use GitHub app
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/S

#1293 Migrate sub to use GitHub app
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#1296 Revert "Migrate sub to use GitHub app"
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#1295 Oss prow: crier and hook use GitHub app only
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/hook-ghapp.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/monitoring/prow_podmonitors.yaml
Labels: approved, lgtm, size/M

#1300 Webhooks from prow app send to hook
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#1287 OSS prow onboarding with GitHub app
  prow/oss/onboarding.md
  prow/oss/oss_prow_logo.png
  prow/oss/oss_prow_logo20X20.png
Labels: approved, lgtm, size/S

#1294 Delete hmac reconciler job
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#1303 Replace stick lgtm team.
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#1310 gcp-guest: remove obsolete postsubmits
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#1309 compute-image-tools: Add presubmit for module tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#1313 Revert "Revert "Migrate sub to use GitHub app""
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#1316 Revert "Revert "Revert "Migrate sub to use GitHub app"""
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#1318 Knative-prow autobump PR not assigned to anyone
  prow/knative/knative-autobump-config.yaml
Labels: approved, lgtm, size/XS

#1321 Bump up both unscheduled and pending timeout
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#1317 Oss-prow autobump PR not assigned to anyone
  prow/oss/oss-autobump-config.yaml
Labels: approved, lgtm, size/XS

#1306 Update test-install-oracle.yaml
  prow/prowjobs/google/bms-toolkit/test-install-oracle-poc.yaml
  prow/prowjobs/google/bms-toolkit/test-install-oracle.yaml
Labels: approved, lgtm, size/M

#1328 Fix typo in the testing file in bms-toolkit repo
  prow/prowjobs/google/bms-toolkit/test-install-oracle-poc.yaml
Labels: approved, lgtm, size/XS

#1322 Use cli-tools-module-tests image for import/export module tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#1325 Add an alert for KES errors.
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/M
