Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-06, with the labels that each got.

#884 Enable html lens on OSS Prow.
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#885 Add TestGrid config presubmit test
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#880 Require self-approval for kubeflow/kubeflow
  prow/oss/plugins.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#888 Add knative slack token as a secret in oss prow
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S

#889 move bentheelder to emeritus
  OWNERS
Labels: approved, lgtm, size/XS

#891 Remove Transfigure jobs
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#887 Automatically posting knative prow deploy message on slack
  prow/oss/cluster/crier.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#894 Fix a typo in crier deployment
  prow/oss/cluster/crier.yaml
Labels: approved, lgtm, size/XS

#895 Revert knative prow slack message
  prow/oss/cluster/crier.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#890 added kfp presubmit v2 test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#897 Revert "Revert "Automatically posting knative prow deploy message on …
  prow/oss/cluster/crier.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#902 Add external secret from build cluster for blueprints
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S

#901 Clarify requirement and expected value of GITHUB_FORK_URI.
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#900 Onboard GoogleCloudPlatform/blueprints repo
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#903 Add build cluster kubeconfig for blueprints
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#904 Add a checkconfig presubmit to validate GoogleCloudPlatform/blueprints in repo config.
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
Labels: approved, lgtm, size/S

#905 Add a prow job config test checking for jobs running on hidden repos
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/M

#906 add core prow config for blueprints
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#908 secrets-store-csi-driver-provider-gcp: configure periodic envvars
  prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
Labels: approved, lgtm, size/XS

#911 Add postsubmit jobs building image for release
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#914 Knative prow: automated deployment
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#916 Add a slack worker on oss prow
  prow/oss/cluster/crier.yaml
Labels: approved, lgtm, size/XS

#921 Revert "Add a slack worker on oss prow"
  prow/oss/cluster/crier.yaml
Labels: approved, lgtm, size/XS

#913 OSS prow: auto deploy at 11:30, skip if no oncall
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#932 Delete update-monitoring job
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#937 expand the teams that can use the prow ui
  prow/knative/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS
