Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-12, with the labels that each got.

#1342 Add instruction for cloning github repos with ssh keys
  prow/oss/onboarding.md
Labels: approved, lgtm, size/S

#1343 Podmonitor also monitors sub
  prow/oss/cluster/monitoring/prow_podmonitors.yaml
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#1340 Remove crier-ghapp and hook-ghapp deployment files
  prow/oss/cluster/crier-ghapp.yaml
  prow/oss/cluster/hook-ghapp.yaml
Labels: approved, lgtm, size/L

#1353 Remove the cla:yes label requirement in Knative Prow config
  prow/knative/cluster/500-cherrypicker.yaml
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#1339 Revert "Revert "Revert "Revert "Migrate sub to use GitHub app""""
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#1359 Update go.mod to use latest test-infra 20211209213704-46d865fbe139
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#1341 gcp-guest: exclude oslogin from CIT
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1367 Prow jobs defined in .yml files are also respected
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#1370 add banner for Prow User Survey (2021 year-end)
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1373 Add alerts for tide sync and status controller heartbeats.
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/M

#1364 pipelines: Add gcp_marketplace presubmit test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1374 Revert "Add alerts for tide sync and status controller heartbeats."
  prow/oss/terraform/modules/alerts/main.tf
Labels: approved, lgtm, size/M

#1379 Revert "add banner for Prow User Survey (2021 year-end)"
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1382 test(kubeflow): kfp integration test v2
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M

#1381 test(kubeflow): remove kubeflow-pipeline-sample-test and kubeflow-pipeline-component-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M
