Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-01, with the labels that each got.

#647 Prometheus alerts send to google group
  prow/knative/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
  prow/oss/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
Labels: approved, lgtm, size/XS

#648 Add jobs to autobump testgrid
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#649 Add image field for canary testgrid autobump job
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#636 oss prow manages hmac token for kubeflow
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#652 Add missing ssh key secret to autobump testgrid jobs
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#653 Register 'build-kubeflow' cluster with OSS-Prow.
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#654 Automatically deploy prow monitoring secrets post submit
  prow/knative/cluster/monitoring/Makefile
  prow/oss/cluster/monitoring/Makefile
Labels: approved, lgtm, size/S

#657 Prow alerts send to test-infra oncall instead of engprod oncall
  prow/knative/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
  prow/oss/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#660 Bump autobumper to working image
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#662 Update generic autobump image for testgrid bump job
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#661 Expose prow monitoring dashboard
  prow/oss/cluster/monitoring/grafana_expose.yaml
Labels: approved, lgtm, size/M

#659 Enable tide reviewApprovedRequired on knative-sandbox/net-contour
  prow/knative/config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#664 Revert "Expose prow monitoring dashboard"
  prow/oss/cluster/monitoring/grafana_expose.yaml
Labels: approved, lgtm, size/M

#665 Bump generic autobumper to use image with fix for testgrid-prod job
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#663 secrets-store-csi-driver-provider-gcp: remove secret
  prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
Labels: approved, lgtm, size/S

#655 Enable trigger plugin for kubeflow repos
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S

#666 Migrate first Kubeflow presubmit test to oss prow
  prow/prowjobs/kubeflow/OWNERS
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#667 Set review_acts_as_lgtm to true for lgtm plugin
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/S

#670 Update kubeflow-presubmits.yaml, rename test
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/XS

#671 added xiyue as kubeflow owner
  prow/prowjobs/kubeflow/OWNERS
Labels: approved, lgtm, size/XS

#672 Correct kubeflow build cluster name
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/XS

#673 fix(kubeflow): add decorate true
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/XS

#674 test(kubeflow): add KFP presubmit tests as optional
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/L

#675 fix(kubeflow): rename kfp presubmits
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/M

#679 Upgrade generic_autobump to v20210125-7ba72b3
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#680 Update testgrid autobump to v20210126-f503f3e
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#676 test(kubeflow): enable tests & tide for kubeflow/pipelines
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/kubeflow/kubeflow-periodics.yaml
  prow/prowjobs/kubeflow/kubeflow-postsubmits.yaml
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/L

#681 test(kubeflow): rename kfp tests to remove v2 suffix
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/M

#682 test(kubeflow): rename kfp tests to be exactly like before
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/S

#683 test(kubeflow): fix kfp tests
  prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Labels: approved, lgtm, size/M

#677 Revert "Revert "Expose prow monitoring dashboard""
  prow/oss/cluster/monitoring/grafana_expose.yaml
Labels: approved, lgtm, size/M

#684 Prow deploy job use latest image, and gcloud beta for secrets
  prow/knative/cluster/monitoring/Makefile
  prow/oss/cluster/monitoring/Makefile
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/S

#687 Configure oss prow grafana exposure to match k8s prow settings
  prow/oss/cluster/monitoring/grafana_expose.yaml
Labels: approved, lgtm, size/S

#688 Only push images when non-cluster files change
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS
