Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-07, with the labels that each got.

#942 Add Workload Metrics PodMonitor resources for oss-prow components.
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/monitoring/prow_podmonitors.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/L

#950 Add announcement banner promoting prow-announce@google.com group.
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#951 Temporarily remove problematic PodMonitor.
  prow/oss/cluster/monitoring/prow_podmonitors.yaml
Labels: approved, lgtm, size/S

#954 Make lgtm sticky for googlers in oss-test-infra and testgrid
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#957 oss prow: add sub component
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/M

#960 Add pubsub testing.
  prow/oss/config.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#967 OSS prow sub: add github token
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/XS

#968 Add missing RBAC for sub
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/S

#991 Seed terraform files
  .gitignore
  prow/oss/terraform/README.md
  prow/oss/terraform/main.tf
  prow/oss/terraform/modules/dashboards/main.tf
  prow/oss/terraform/modules/dashboards/variables.tf
Labels: approved, lgtm, size/L
