Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-09, with the labels that each got.

#1082 Add build cluster kubeconfig for looker-32
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M, ok-to-test, kind/oncall-hotlist

#1079 Switch Deck Private instance from hidden only to tenantID
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#1085 Revert "Switch Deck Private instance from hidden only to tenantID"
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#1090 Adding new build clusters to allowed list
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#1088 Update rbac.authorization.k8s.io to v1
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/sub.yaml
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/M

#1091 Add missing settings for looker-build-16 and 32
  prow/oss/config.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#1089 Knative prow: update rbac.authorization.k8s.io to v1
  prow/knative/cluster/301-rbac.yaml
  prow/knative/cluster/400-prow-controller-manager.yaml
  prow/knative/cluster/build/301-rbac.yaml
Labels: approved, lgtm, size/M

#1098 Switch Deck Private instance from hidden only to tenantID
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#1106 Add blueprints managed cert to new ingress
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/S

#1109 Change static ip for blueprints ingress
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#1116 bump crier to v20210914-d9fade61b4
  prow/oss/cluster/crier.yaml
Labels: approved, lgtm, size/XS

#1115 oss-prow: move crier and tide to dedicated nodepool
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/M

#1114 remove Knative Milestone Maintainers
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1118 Roll back crier to v20210908-3a373c2cdd
  prow/oss/cluster/crier.yaml
Labels: approved, lgtm, size/XS

#1119 Add redirect to blueprints deck
  prow/oss/cluster/deck_blueprints_deployment.yaml
Labels: approved, lgtm, size/XS

#1121 Revert "oss-prow: move crier and tide to dedicated nodepool"
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/M

#1122 Add redirect to blueprints oauth proxy
  prow/oss/cluster/deck_blueprints_deployment.yaml
Labels: approved, lgtm, size/XS

#1124 Create new blueprints oauth secrets for new oauth app
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/M

#1125 Update GCP alert recipient to prow-alert-pioneer
  prow/oss/terraform/main.tf
Labels: approved, lgtm, size/XS

#1126 Bump crier for allowing skip comment on PR
  prow/oss/cluster/crier.yaml
Labels: approved, lgtm, size/XS

#1127 Opting out looker/helltool from bot commenting job failure
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1110 Update ingress apiversion to networking.k8s.io/v1
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#1132 Rotate Prow deployments to a new oauth token.
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/sub.yaml
  prow/oss/cluster/tide.yaml
Labels: approved, lgtm, size/S

#1133 Revert "Update ingress apiversion to networking.k8s.io/v1"
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#1136 Add blueprints tenantID
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1138 Revert "Update oss-prow to v20210917-ee1e7c845b"
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/sub.yaml
  prow/oss/cluster/tide.yaml
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/M

#1137 Blueprints tests redirect to private front end
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1142 osconfig-presubmit-build: test deb10 instead of deb9
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1149 Update Knative Boskos reaper expire to 11min to recycle the resources more efficiently
  prow/knative/cluster/build/400-boskos-reaper.yaml
Labels: approved, lgtm, size/XS

#1062 knative build cluster: update external secret to 8.3.0
  prow/knative/cluster/build/500-kubernetes-external-secrets_crd.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_deployment.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_rbac.yaml
Labels: approved, lgtm, size/L

#1034 Add boskos alerts
  prow/oss/terraform/README.md
  prow/oss/terraform/modules/alerts/boskos/main.tf
  prow/oss/terraform/modules/alerts/boskos/variables.tf
Labels: approved, lgtm, size/L

#1152 Decrease Sub replicas from 10 to 2
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/XS

#1155 Configure a more appropriate rolling update for Sub.
  prow/oss/cluster/sub.yaml
Labels: approved, lgtm, size/XS

#1156 Looker opt in summary comment
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS
