Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-04, with the labels that each got.

#765 Add unit tests for google-cloud component
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#763 Oss prow: enable secret managed by kubernetes external secrets
  prow/oss/README.md
  prow/oss/cluster/kubernetes-external-secrets_crd.yaml
  prow/oss/cluster/kubernetes-external-secrets_deployment.yaml
  prow/oss/cluster/kubernetes-external-secrets_rbac.yaml
  prow/oss/cluster/kubernetes-external-secrets_service.yaml
  prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/external_secret_alerts.libsonnet
  prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/oss/cluster/monitoring/prow_servicemonitors.yaml
  prow/oss/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml
Labels: approved, lgtm, size/L

#757 remove guest postsubmit builds
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#768 add fly validate to concourse dir
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#769 test(kubeflow): kfp samples v2 test should trigger on sample change
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#771 Horologium: update RBAC with newly required permission
  prow/knative/cluster/301-rbac.yaml
  prow/oss/cluster/horologium.yaml
Labels: approved, lgtm, size/XS

#770 Allow PRs created by knative-prow-updater-robot to be automatically merged
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#764 Knative prow: enable secret managed by kubernetes external secrets
  prow/knative/README.md
  prow/knative/cluster/200-serviceaccounts.yaml
  prow/knative/cluster/500-kubernetes-external-secrets_crd.yaml
  prow/knative/cluster/500-kubernetes-external-secrets_deployment.yaml
  prow/knative/cluster/500-kubernetes-external-secrets_rbac.yaml
  prow/knative/cluster/500-kubernetes-external-secrets_service.yaml
  prow/knative/cluster/monitoring/mixins/lib/config.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/external_secret_alerts.libsonnet
  prow/knative/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
  prow/knative/cluster/monitoring/prow_servicemonitors.yaml
Labels: approved, lgtm, size/L

#775 Revert oss-prow deck to v20210412-ed35ec0cee
  prow/oss/cluster/deck.yaml
Labels: approved, lgtm, size/XS

#776 Patch deck to v20210419-68a26a452c
  prow/oss/cluster/deck.yaml
Labels: approved, lgtm, size/XS

#778 Revert "[ESPv2] Switch kubekins versions to GKE regular release channel"
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#779 Switch gke version to channel regular
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#781 Add external secret for github oauth2 secrets in preparation for private deck deployment
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/M

#784 Try ci/latest-1.18
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#786 Update presubmit test image to use go1.15
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#785 Update go deps: update deps from k8s/test-infra
  go.mod
  go.sum
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/XXL

#783 Add private deck deployment to oss prow
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/config.yaml
Labels: approved, lgtm, size/L

#787 Onboarding chaotoppicks org: setting up webhook and accept invitation
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#788 Update hmac version with latest fix
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#789 Fix a typo in private oss prow deck managed cert config
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS

#791 Correct hmac image version that contains all fixes
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#792 Deploy private deck in default namespace, btw change them to clusterI…
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/S

#794 Opt testgrid into automatic webhook management
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#793 Add back private deck certmanager and ingress
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/S

#795 Private deck deployment uses KUBECONFIG env var
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#797 Add missing mounts to private deck
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/S

#798 Configure managed webhooks for esp-v2 repo.
  prow/oss/config.yaml
Labels: approved, lgtm, size/S

#799 Remove host from oss prow ingress
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/S

#800 Add compute-image-tools to deck.additional_allowed_buckets
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#802 fix compute-image-tools-test bucket
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#803 ESPv2: use `gke-channel-regular`
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#801 Convert all existing webhooks to be managed by hmac tool
  prow/oss/config.yaml
Labels: approved, lgtm, size/S

#804 Change deck service to use nodeport
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#807 Enable kes in knative build cluster
  prow/knative/cluster/build/200-serviceaccounts.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_crd.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_deployment.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_rbac.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_service.yaml
Labels: approved, lgtm, size/L

#808 Knative prow: add more detailed instruction on how to use KES
  prow/knative/README.md
Labels: approved, lgtm, size/S

#796 Update create build cluster script for auto create PR
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#805 Add back private deck ingress #3
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/S

#812 Fix private deck deployment with oauth2 fixes
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#813 Fix the typo introduced in deck private deployment
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#738 automatic packagebuild ps
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#790 Enable inrepoconfig for chaotoppicks org
  go.mod
  go.sum
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/chaotoppicks/great-private-tools/great-private-tools.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/chaotoppicks/great-tools/great-tools.yaml
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/L

#816 Add external secret from build cluster for looker-private
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S

#817 Add build cluster kubeconfig for looker-private
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#818 Fix Looker GCS bucket name.
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#819 Fix a typo in private org name
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#815 Turn down default hmac
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#821 Add a separate SA for public Deck to distinguish from other control plane components.
  prow/oss/cluster/deck.yaml
Labels: approved, lgtm, size/XS

#822 Switch public Deck to use new SA.
  prow/oss/cluster/deck.yaml
Labels: approved, lgtm, size/S

#820 Fixing config checking jobs for private repos
  prow/prowjobs/private-inrepoconfig-configcheck/chaotoppicks/great-private-tools/great-private-tools.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/chaotoppicks/great-tools/great-tools.yaml
Labels: approved, lgtm, size/S

#823 Fix Deck RBAC by updating service account ref.
  prow/oss/cluster/deck.yaml
Labels: approved, lgtm, size/XS

#824 Make Tide data available to private Deck.
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#825 Disable global cluster for inrepoconfig
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS
