Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2021-03, with the labels that each got.

#718 test(kubeflow): migrate kubeflow on gcp oss prow completely
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/kubeflow/testing/kubeflow-testing.yaml
Labels: approved, lgtm, size/M

#721 test(kubeflow): add testgrid config
  prow/prowjobs/kubeflow/gcp-blueprints/kubeflow-gcp-blueprints.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  testgrid/config.yaml
Labels: approved, do-not-merge/hold, lgtm, size/M

#720 Add --github-token-path flag to cherrypicker
  prow/knative/cluster/500-cherrypicker.yaml
Labels: approved, lgtm, size/XS

#724 test(kfp): add run_if_changed config for mkp presubmit
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#725 add apt transport
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#726 add yum-plugin repo
  prow/oss/config.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#727 add jobs for new guest repos
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#728 [grpc-transcoder] Add Prow setup for grpc-transcoder
  prow/oss/plugins.yaml
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/OWNERS
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#729 Add mpherman2 to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#731 Update knative config validate job to use main branch
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#732 test(kubeflow): better run_if_changed conditions
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#733 Remove Exposure Notification servers and configuration
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/google/exposure-notifications-server/OWNERS
  prow/prowjobs/google/exposure-notifications-server/en-server.yaml
  prow/prowjobs/google/exposure-notifications-verification-server/OWNERS
  prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/L

#736 Replace /k8s-testimages/ autobumper image with /k8s-prow/ image
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#737 Fix command name being different for k8s-prow autobump image
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#739 test(kubeflow): more accurate run_if_change for kubeflow-pipeline-mkp-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#740 Update oss prow plugins to new form
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/L

#741 Update knative prow plugins to new form
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/L

#745 Add oss-prow onboarding docs.
  README.md
  prow/oss/README.md
  prow/oss/onboarding.md
Labels: approved, lgtm, size/L

#742 [http-pattern-matcher] Add Prow setup for google/http_pattern_matcher
  prow/oss/config.yaml
  prow/prowjobs/google/http_pattern_matcher/OWNERS
  prow/prowjobs/google/http_pattern_matcher/http-pattern-matcher.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#747 Serve plugin config from Deck.
  prow/knative/cluster/400-deck.yaml
  prow/oss/cluster/deck.yaml
Labels: approved, lgtm, size/S

#749 [http-pattern-matcher] Update branch name
  prow/prowjobs/google/http_pattern_matcher/http-pattern-matcher.yaml
Labels: approved, lgtm, size/XS

#748 OSS prow: upgrade prometheus operator from 0.29.0 to 0.45.0
  prow/oss/cluster/monitoring/Makefile
  prow/oss/cluster/monitoring/prometheus-operator-crds/README.md
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagerconfigs.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagers.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_podmonitors.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_probes.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheuses.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheusrules.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_servicemonitors.yaml
  prow/oss/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_thanosrulers.yaml
  prow/oss/cluster/monitoring/prometheus_operator_deployment.yaml
  prow/oss/cluster/monitoring/prometheus_operator_rbac.yaml
  prow/oss/cluster/monitoring/prow_alertmanager.yaml
  prow/oss/cluster/monitoring/prow_prometheus.yaml
Labels: approved, lgtm, size/XXL

#750 Knative prow: upgrade prometheus operator from 0.29.0 to 0.45.0
  prow/knative/cluster/monitoring/Makefile
  prow/knative/cluster/monitoring/prometheus-operator-crds/README.md
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagerconfigs.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_alertmanagers.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_podmonitors.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_probes.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheuses.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_prometheusrules.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_servicemonitors.yaml
  prow/knative/cluster/monitoring/prometheus-operator-crds/monitoring.coreos.com_thanosrulers.yaml
  prow/knative/cluster/monitoring/prometheus_operator_deployment.yaml
  prow/knative/cluster/monitoring/prometheus_operator_rbac.yaml
  prow/knative/cluster/monitoring/prow_alertmanager.yaml
  prow/knative/cluster/monitoring/prow_prometheus.yaml
Labels: approved, lgtm, size/XXL

#751 Knative prow monitoring secret: updated with a script instead of make…
  prow/knative/cluster/monitoring/Makefile
  prow/knative/cluster/monitoring/secrets/replace-secrets-from-gcp.sh
Labels: approved, lgtm, size/M

#752 OSS prow monitoring secret: updated with a script instead of make rule
  prow/oss/cluster/monitoring/Makefile
  prow/oss/cluster/monitoring/secrets/replace-secrets-from-gcp.sh
Labels: approved, lgtm, size/M

#746 config(kubeflow): kubeflow/pipelines require self approval for PRs
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#755 test(kubeflow): kubeflow-pipelines-v2-samples-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#756 test(kubeflow): enable kubeflow-pipelines-samples-v2 test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#758 test(kubeflow): set up presubmit for kubeflow/internal-acls
  prow/prowjobs/kubeflow/internal-acls/kubeflow-internal-acls.yaml
Labels: approved, lgtm, size/S

#759 test(kubeflow): add missing decorate=true to kubeflow-internal-acls test
  prow/prowjobs/kubeflow/internal-acls/kubeflow-internal-acls.yaml
Labels: approved, lgtm, size/XS

#760 test(kubeflow): add kubeflow-pipelines-manifests test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S
