Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-01, with the labels that each got.

#1390 fix(pipelines): file not found for marketplace snapshot test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1393 pipelines: enable e2e test for frontend changes
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1400 Enable github workflows retest in knative repos
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1398 pipelines: Merge two commands to one line for mkp-snapshot-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1419 test(pipelines): Update test config to accommodate code move for v2.
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#1423 gcp-guest: remove han from owners
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS

#1425 test(pipeline): Use golang image for kubeflow-pipeline-backend-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1422 gcp-blueprints: Run postsubmit only when it is master branch or release branch
  prow/prowjobs/kubeflow/gcp-blueprints/kubeflow-gcp-blueprints.yaml
Labels: approved, lgtm, size/XS

#1428 test(pipelines): fix kubeflow-pipeline-backend-test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1430 Upgrade ingresses to networking.k8s.io/v1.
  prow/knative/cluster/400-ingress.yaml
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/M

#1431 Update KES deployments and CRDs for K8s 1.22+.
  prow/knative/cluster/500-kubernetes-external-secrets_crd.yaml
  prow/knative/cluster/500-kubernetes-external-secrets_deployment.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_crd.yaml
  prow/knative/cluster/build/500-kubernetes-external-secrets_deployment.yaml
  prow/oss/cluster/kubernetes-external-secrets_crd.yaml
  prow/oss/cluster/kubernetes-external-secrets_deployment.yaml
Labels: approved, lgtm, size/XL

#1426 Update kubeflow/OWNERS
  prow/prowjobs/kubeflow/OWNERS
Labels: approved, lgtm, size/XS

#1433 Add missing RBAC for KES
  prow/knative/cluster/500-kubernetes-external-secrets_rbac.yaml
  prow/oss/cluster/kubernetes-external-secrets_rbac.yaml
Labels: approved, lgtm, size/S

#1432 Update ProwJob CRDs to use schema and apply with --server-side=true.
  prow/knative/Makefile
  prow/knative/cluster/300-crds.yaml
  prow/knative/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  prow/oss/Makefile
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
Labels: approved, lgtm, size/XXL

#1429 test(pipelines): use golang:1.17.6-bullseye for backend presubmit
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1436 test(pipelines): restore v2 presubmit tests to always run
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS
