Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-08, with the labels that each got.

#1707 Create build cluster script recommends user to override owner of the …
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#1706 Remove mentioning of secret sharing from create-build-cluster.sh
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#1709 experimental bump kind to 0.14.0
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1710 Revert "experimental bump kind to 0.14.0"
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1716 only run KFP SDK code style presubmits against master base branch
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1719 bump kind to 0.14.0 in config sync presubmits
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1725 Add external secret from build cluster for cloud-kubernetes-node-management-team
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/gencred-config/gencred-config.yaml
Labels: approved, lgtm, size/S

#1726 Add build cluster kubeconfig for cloud-kubernetes-node-management-team
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#1728 increase CS e2e memory request to 80Gi
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1730 Reduce frequency of Guest Policy and OS Policy Assignments cleanup
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/S

#1732 Add in presubmit tests for kubeflow/pipelines for python v3.10
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#1735 skip e2e on non-functional changes
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1736 add docs and dashboard dir to skip regex
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1737 Update ESPv2 jobs to use python3
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M
