Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-11, with the labels that each got.

#1824 Add Prow setup for jwt_verify_lib
  prow/prowjobs/google/jwt_verify_lib/OWNERS
  prow/prowjobs/google/jwt_verify_lib/jwt-verify-lib-presubmit.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/M

#1826 remove monorepo presubmits
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/S

#1827 remove monorepo periodics
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#1828 Update google/jwt_verify_lib CI image
  prow/prowjobs/google/jwt_verify_lib/jwt-verify-lib-presubmit.yaml
Labels: approved, lgtm, size/XS

#1830 remove --multirepo flag
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1831 Update jwt_verify_lib CI image
  prow/prowjobs/google/jwt_verify_lib/jwt-verify-lib-presubmit.yaml
Labels: approved, lgtm, size/XS

#1833 remove PROBER_DOCKER_ARGS
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1839 Update ESPv2 image deploy type to default COS_CONTAINERD
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1835 make KFP SDK execution tests required
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1842 chore: Increase timeout for kpt-config-sync autopilot periodics
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#1843 Run `kubeflow-pipelines-tfx-python37` tests only on `sdk/release-1.8` branch.
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1844 Remove shybeka and swasik from OWNERS.
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/OWNERS
Labels: approved, lgtm, size/XS

#1846 [ESPv2] Update prow env to image with LLVM 14
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M
