Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-07, with the labels that each got.

#1683 Add prowjobs for kpt-config-sync
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/OWNERS
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-utils.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/L, ok-to-test

#1685 add kubeflow pipelines sdk code style checks
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M

#1686 add workload identity config to kpt-config-sync
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1689 bump to kubekins on version 1.23
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1687 Add new distros to presubmits including arm64.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#1692 require KFP SDK code style checks
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#1694 add kind volume mounts
  prow/oss/config.yaml
Labels: approved, lgtm, size/S

#1704 Change cleanup to remove resources older than 12 hours.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS
