Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-04, with the labels that each got.

#1574 Add plank config for compute-image-import-prow
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1572 Add external secret from build cluster for compute-image-import
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/S

#1573 Add build cluster kubeconfig for compute-image-import
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#1575 Onboard compute-image-import's jobs
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/OWNERS
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/L

#1578 Add guestos-metadata-scanner to cleanerupper
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#1581 Compute image import: Use main branch
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml
Labels: approved, lgtm, size/XS

#1585 Remove windows upgrade; this is staying with compute-image-tools
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml
Labels: approved, lgtm, size/S

#1587 Remove import/export jobs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/L

#1591 Configure ingress and managed certs for gprow.dev domain.
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/M

#1593 Fix 'grow' 'gprow' typo in ingress definition.
  prow/oss/cluster/cluster.yaml
Labels: approved, lgtm, size/XS
