Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-10, with the labels that each got.

#1778 Configure the correct zone and region for the config sync test on autopilot clusters
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/M

#1779 Increase the periodic job running time from 2h to 3h
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1780 set GCP_PROJECT to stolos-dev in presubmits
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1783 add tide merge labels
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1784 add tide labels to plugins.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#1786 experimental: use workload identity for periodic
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1787 use empty string for PROBER_DOCKER_ARGS
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1789 Update survey banner to reflect new deadline
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1790 switch periodic jobs to use workload identity
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#1797 Add bitbucket and gitlab jobs for config-sync
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/L

#1798 Update ESPv2 kubekins images to public URL
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#1795 Add more CI tests for config-sync
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/M

#1801 Update the make target name for config-sync jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1802 Decrease the memory request for config sync Kind prow jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1806 use custom labels for presubmit nodeSelector
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#1805 set env USE_TEST_INFRA_LOG_DUMPING
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#1808 revert survey banner
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#1813 remove secret rotation job
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-utils.yaml
Labels: approved, lgtm, size/M

#1814 Increase the periodic job timeout from 3h to 4h
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1817 Update gcloud-in-go version to latest
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#1819 Use k8s-staging-test-infra version of gcloud-in-go
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#1734 Remove optional and skip_reports from kubeflow/pipelines for Python v3.10 as tests are verified as passing
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#1821 test kfp sdk on python 3.11
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S
