Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-06, with the labels that each got.

#1637 Update espv2 image with latest tooling
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1639 Pin oauth2 image version to v7.2.1
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/XS

#1642 Update kubeflow-pipelines-presubmits.yaml: use Py3.7 for kubeflow-pipelines-component-yaml, remove Py2.7 test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#1644 Delete prow job from looker so that the other configs can be removed
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/S

#1530 Remove Looker Prow jobs
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck_private_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Labels: approved, lgtm, size/L, needs-ok-to-test

#1646 Remove private frontend for Looker
  prow/oss/cluster/cluster.yaml
  prow/oss/cluster/deck_private_deployment.yaml
Labels: approved, lgtm, size/L

#1649 Update ESPv2 e2e images
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1650 Fix ESPv2 cluster CIDR range
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/S

#1652 Update testgrid OWNERS
  prow/prowjobs/GoogleCloudPlatform/testgrid/OWNERS
Labels: approved, lgtm, size/XS

#1651 Update testgrid bazel images to include 5.2.0
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
Labels: approved, lgtm, size/XS

#1654 Enable inrepoconfig for testgrid repo
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
Labels: approved, lgtm, size/S

#1655 Remove pull-testgrid-all job
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
Labels: approved, lgtm, size/S

#1662 update build targets for guest agent
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1663 correct typo
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1664 Update prow plugins for compute-image-import.
  prow/oss/config.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S

#1668 External secret for build-kpt-config-sync is in oss-prow project
  prow/oss/cluster/kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/XS

#1667 Add build cluster kubeconfig for kpt-config-sync
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test
