Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2022-03, with the labels that each got.

#1494 gcp-guest: prune creds, extra_refs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#1497 gcp-guest: add legacy periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/L

#1498 gcp-guest: add legacy periodics commands
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/L

#1501 gcp-guest: update cit location
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1502 gcp-guest: override creds environment variable
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/M

#1505 gcp-guest: fix osconfig-tests entrypoint
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#1506 gcp-guest: add env var trick
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
Labels: approved, lgtm, size/XS

#1507 gcp-guest: env trick for cleanerupper
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#1512 Updates rerun auth to use slugs instead of ids
  prow/knative/config.yaml
Labels: approved, lgtm, size/S, ok-to-test

#1513 Update guest tests with current distros.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1514 Separate knative prow reruns by org
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1517 Fix the rerun_auth_configs for Knative
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#1519 gcp-guest: no codecov
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#1524 Update Prow job age and max pod age for Knative Prow
  prow/knative/config.yaml
Labels: approved, lgtm, size/XS

#1523 Add 2 external secrets for knative build cluster
  prow/knative/cluster/build/600-kubernetes_external_secrets.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#1531 cleanerupper: Run every hour
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#1536 disable ci-images-import-export-cli-e2e-tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/S

#1541 Correct sticky team name.
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#1544 Re-enable import/export tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/M

#1547 Increase timeout for OVF tests; remove v2v tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/M

#1548 use gcr.io/gcp-guest for cleanerupper
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#1554 Remove Prow config for google/knative-gcp
  prow/knative/config.yaml
  prow/knative/plugins.yaml
Labels: approved, lgtm, size/M

#1555 ESPv2: update build image
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1553 Migrate Knative Prow to a GitHub app
  prow/knative/cluster/400-crier.yaml
  prow/knative/cluster/400-hook.yaml
  prow/knative/cluster/400-ingress.yaml
Labels: approved, lgtm, size/M

#1559 Move Knative Tide to authenticate as a GitHub app
  prow/knative/cluster/400-tide.yaml
Labels: approved, lgtm, size/S
