Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2023-11, with the labels that each got.

#2107 Remove windows-2019-core-for-containers
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2110 Update gcp-guest owners.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS

#2112 Bump windows upgrade testing timeout to 11hrs and change the rate to …
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#2109 Adding OSConfig test coverage for Rocky, OpenSuse and SLES
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#2116 Revamp guest-test-infra presubmit checks
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#2115 fix: update broken link
  README.md
Labels: approved, lgtm, size/S

#2121 disable review_acts_as_lgtm for kpt-config-sync
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2117 add rgraph branch to presubmits
  prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1912 update-image-import-owners
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/OWNERS
Labels: approved, lgtm, size/XS

#2124 add KFP SDK Python 3.12 presubmits
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M

#2125 add manual k8s CronJob to regularly restart KES
  prow/oss/cluster/kes-kicker.yaml
Labels: approved, lgtm, size/M

#2128 kes-kicker: target 'default' namespace
  prow/oss/cluster/kes-kicker.yaml
Labels: approved, lgtm, size/XS
