Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2023-06, with the labels that each got.

#1965 Update transcoding.yaml
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml
Labels: approved, lgtm, size/XS

#1967 add config sync periodics for parallel gke
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/M

#1968 update num clusters env var name
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1969 fix: use region for autopilot clusters
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1971 explicitly unset GCP_ZONE for autopilot
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1973 bump gke-e2e image for junit binary
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1974 experiment with larger num clusters for gke
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1975 experiment with more autopilot clusters
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#1979 update experimental e2e jobs to use lazy create
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/L

#1981 increase interval for new cs e2e jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS
