Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2023-08, with the labels that each got.

#2032 Revert "add kfp-dsl runtime presubmit tests"
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M

#2037 Add a CI job for ConfigSync stress test on Autopilot rapid-latest
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2035 remove release branch periodics
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/XXL

#2036 add release branch CI for v1.16
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/L

#2039 bump release CI from pinned tag to branch
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/XS

#2041 Update gcp-guest owners.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS

#2042 add presubmit tests for kfp runtime code
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M

#2049 Update gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S
