Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2023-01, with the labels that each got.

#1863 add Config Sync release periodics
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/XXL

#1865 fix typo in project name
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/XS

#1867 use e2e-prow image from build cluster project
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/XS

#1871 Extend 7-autopilot-rapid-latest timeout to 5h
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/S, ok-to-test

#1873 Add Anthony to Owners
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS

#1858 Add sbom presubmit for disk export workflow modification
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/S

#1874 Add quotation
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#1877 Add gkcalat to `prow/prowjobs/kubeflow/OWNERS`
  prow/prowjobs/kubeflow/OWNERS
Labels: approved, lgtm, size/XS

#1878 Increase the timeout for release CI jobs on autopilot clusters
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/S

#1880 Increase the timeout for config sync test-group 4 CI jobs on autopilot clusters
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#1885 Update guest owners file.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/S
