Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2023-07, with the labels that each got.

#1984 Update gcpproxy-prow image to latest build with go1.20.5
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1986 add standard-rapid CS periodic using new job type
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/M

#1987 Update gcpproxy-prow image to include llvm compiler-rt
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1988 move new CS periodics to main dashboard
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/S

#1991 set cluster shape for new jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#1992 add remaining CS prowjobs using new job type
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/L

#1993 Enable windows sbom presubmit
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/S

#1995 Update gcpproxy-prow image with Go1.20.5
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#1999 chore: bump CS kubekins-e2e image
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/S

#1989 Add compute-image-windows to OSS prow.
  prow/oss/config.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S

#2000 Use secret for powershell variable instead of hard coded value
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/S

#2004 load shell variable before daisy command for presubmit
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2005 Use the absolute path to shell
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2006 Use shell command on new docker image
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2007 Separate parts of cmd for shell parsing
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2008 Use bash instead of sh
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2009 Run bash as a command
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2011 Run bash and daisy in one command
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/XS

#2012 cleanup sharded prowjobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/XXL

#2013 Use secrets for windows sbom presubmit
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Labels: approved, lgtm, size/S

#2014 move vulnerability-scan to main testgrid
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2015 Update the vulnerability-scanner image
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2019 increase cluster size for stress tests
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2021 add run all gcpc modules presubmit test for kfp sdk
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S
