Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2023-09, with the labels that each got.

#2054 Unregister bms-oracle-team BYO build cluster
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#2050 Add external secret from build cluster for bms-oracle-team
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/gencred-config/gencred-config.yaml
Labels: approved, lgtm, size/S

#2051 Add build cluster kubeconfig for bms-oracle-team
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#2056 Revert incorrect onboarding in PRs 2051 and 2050
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/gencred-config/gencred-config.yaml
Labels: approved, lgtm, size/M

#2057 Add external secret from build cluster for bms-oracle-team
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/gencred-config/gencred-config.yaml
Labels: approved, lgtm, size/S

#2058 Add build cluster kubeconfig for bms-oracle-team
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#2055 Cit 12 hour performance periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2061 Exclude shape validation from cit periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2063 add gke-gcloud-auth-plugin kubeconfig file for the oss-prow
  prow/Makefile.gcloud.mk
  prow/oss/kubeconfigs.yaml
Labels: approved, lgtm, size/M

#2065 fix kubeconfig for test-infra-trusted cluster
  prow/Makefile.gcloud.mk
  prow/oss/Makefile
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
  prow/oss/cluster/prow-controller-manager.yaml
Labels: approved, lgtm, size/S

#2066 mount kubeconfigs configmap into other prow components
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#2067 Update the kubekins-e2e and gke-e2e image for kpt-config-sync
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/S

#2068 kfp: restore sdk-execution-test as required test
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#2069 fix: add missing character to gke-e2e tag
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2072 Add windows and partner images to CIT performance periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2076 Bump cit-performance-peridiocs timeout to 5h to accomodate windows images
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2075 Exclude storageperfbalanced once it is out
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2079 Update gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2082 Run citpresubmit container when cit contents are changed
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2083 Update gcp-guest-config.yaml test suites
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2087 Revert "Update oss-prow to v20230927-f8b8856dbc"
  .prow/presubmits.yaml
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/sub.yaml
  prow/oss/cluster/tide.yaml
  prow/oss/config.yaml
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
Labels: approved, size/M
