Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-03, with the labels that each got.

#2212 Run ubuntu daily cit in compute-image-test-pool projects
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2214 Split ubuntu daily cit dashboard into performance and shapevalidation
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2216 Switch to alerting via email
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2217 Bump cit-periodics broken-column-threshold to 1.5%
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2219 Fix issues with cit alerting configuration
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2220 Only configure alerting thresholds on prow annotations
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2228 Change the default Git provider to CSR
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2226 Update CIT alerting config
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2230 Run performance periodics on a longer, lower interval
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2233 Tune E2E_NUM_CLUSTERS for kpt-config-sync CI to decrease parallism
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS
