Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-11, with the labels that each got.

#2403 Add cit-periodics-accelerator-images config
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2408 Switch to prod CentOS Stream 9 aarch64 image.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2410 Use guestos A3Ultra reservations for accelerator image prow runs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M
