Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-07, with the labels that each got.

#2306 chore: remove kubeflow-pipelines-components-google-cloud-python38
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#2314 chore: bump config-sync gke-e2e image
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2315 chore: bump Config Sync presubmit images
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#2319 chore: use renamed config-sync test targets
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/S

#2323 enable MTU workaround for dind presets
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#2324 add node label selectors to all CS jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-terraform.yaml
Labels: approved, lgtm, size/S

#2325 chore: sync kind periodics with presubmits
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2313 chore: Remove KFP presubmit SDK Execution test prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2301 Removed mkp tests
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#2304 chore: Remove KFP presubmit kfp-kubernetes-execution-tests tests prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2310 chore: Remove KFP presubmit SDK YAPF test prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2316 Removed kubeflow-pipelines-backend-visualization
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2318 chore: Remove KFP presubmit SDK Runtime tests prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#2328 Add a prowjob for gke-networking-api.
  prow/oss/config.yaml
  prow/oss/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/gke-networking-api/OWNERS
  prow/prowjobs/GoogleCloudPlatform/gke-networking-api/gke-networking-api-config.yaml
Labels: approved, lgtm, size/S

#2330 cit-periodics: stop testing mdsmtls
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2317 chore: Remove KFP presubmit SDK Upgrade test prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2329 chore: Remove KFP presubmit SDK tests prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#2327 chore: Remove KFP presubmit SDK misc tests prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test

#2332 Update gcpproxy-prow to latest image
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#2335 chore: Remove KFP presubmit kubeflow-pipelines-samples-v2 test prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2307 Removed kubeflow-pipeline-upgrade-test from Kubeflow Pipelines tests
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, ok-to-test

#2322 chore: Remove KFP presubmit library tests prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, ok-to-test
