Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-05, with the labels that each got.

#2264 Update OWNERS for prow/prowjobs/GoogleCloudPlatform/esp-v2/OWNERS
  prow/prowjobs/GoogleCloudPlatform/esp-v2/OWNERS
Labels: approved, lgtm, size/XS

#2265 chore: bump release branch CI to v1.18
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/L

#2267 Change the default Git provider to CSR
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/S

#2266 Temporarily make KFP e2e test and upgrade test non-blocking
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#2268 Update ESPv2 prow image
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#2260 Enable N4 in cit periodics filters
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2272 Add ubuntu 2410 to ubuntu-daily CIT runs
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2271 Require self-approval for Kubeflow repos
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S, ok-to-test

#2273 Add always pull image param for better debugging and iterating.
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/L

#2274 chore(kubeflow): Remove Google CLA check for kubeflow.
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#2275 Update ESPv2 prow image to version . The previous prow didn't work be…
  prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Labels: approved, lgtm, size/M

#2277 Onboard github.com/GoogleCloudPlatform/cloud-image-tests to prow
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2278 Update cloud image test presubmits
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/cloud-image-tests.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2282 ci: use local git provider as default for CS jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/M

#2281 Pin to a specific cluster version for Autopilot rapid and rapid-latest
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2284 chore: Bump python version for Kubeflow Pipelines CI
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2293 Add CIT period tests for packageupgrade test
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S
