Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-08, with the labels that each got.

#2340 bump test image for gke-networking-api
  prow/prowjobs/GoogleCloudPlatform/gke-networking-api/gke-networking-api-config.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#2341 Update image locations to use new locations.
  .prow/presubmits.yaml
  prow/bump.sh
  prow/oss/README.md
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/gerrit.yaml
  prow/oss/cluster/ghproxy.yaml
  prow/oss/cluster/grandmatriarch_default.yaml
  prow/oss/cluster/grandmatriarch_test-pods.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/horologium.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
  prow/oss/cluster/sub.yaml
  prow/oss/cluster/tide.yaml
  prow/oss/config.yaml
  prow/oss/oss-autobump-config.yaml
  prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
  prow/tests/jobs_test.go
Labels: approved, lgtm, size/L, ¯\_(ツ)_/¯

#2331 Add transfer Issue plugin to Kubeflow repos
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S, ok-to-test

#2342 Update OWNERS.
  .prow/OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#2344 Revert "cit-periodics: stop testing mdsmtls"
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2339 Clean load balancers in guest os projects
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#2336 chore: Remove KFP presubmit kubeflow-pipelines-manifests tests prow config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2348 Revert "Revert "cit-periodics: stop testing mdsmtls""
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2349 Update kubekins-e2e image
  prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml
Labels: approved, lgtm, size/XS

#2350 Update gcp-guest-config.yaml to remove windows-10-20h2-x64 as it's EOL
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2351 Remove debian-11-arm64 from cit-periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2337 ci: add prowjob for Config Sync githubapp
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2354 Add image pull policy to always for prow/prowjobs/grpc-ecosystem/grpc…
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/OWNERS
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml
Labels: approved, lgtm, size/XS

#2355 minimize concurrent AR repo creates/deletes
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2356 Bump the Config Sync release branch to v1.19
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/M

#2357 Add Elliot-xq to OWNERs file for grpc transcoding and espv2.
  prow/prowjobs/GoogleCloudPlatform/esp-v2/OWNERS
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/OWNERS
Labels: approved, lgtm, size/XS

#2358 Use default application credentials with autobump
  prow/oss/oss-autobump-config.yaml
Labels: approved, lgtm, size/XS

#2359 Change grpc-httpjson-transcoding prow image to be same as ESPv2
  prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml
Labels: approved, lgtm, size/XS
