Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-10, with the labels that each got.

#2391 Mark optional jobs in gke-networking-api.
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#2393 Onboard google-guest-agent to Prow
  prow/oss/plugins.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
Labels: approved, lgtm, size/M

#2396 Trigger presubmits for galog and google-guest-agent on any file change, not just go files
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/galog.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
Labels: approved, lgtm, size/S

#2397 Removing performance tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2398 google-guest-agent: turn to using the build system
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
Labels: approved, lgtm, size/XS

#2399 google-guest-agent: update the build call
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
Labels: approved, lgtm, size/XS

#2400 google-guest-agent: enable verbose mode builds
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
Labels: approved, lgtm, size/XS

#2401 google-guest-agent: enable windows check and build
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
Labels: approved, lgtm, size/M

#2392 Update Tide configuration to require ci-passed label for PR merges in Kubeflow repository
  prow/oss/config.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test
