Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-02, with the labels that each got.

#2181 Increase parallel count for oslogin periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2169 k8s-config-connector: enable lifecycle commands
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2186 ci: add helm/oci provider options for CS e2e
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2185 remove ubuntu 2304 images
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2189 Migrating Image Import Containers for all tests
  prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml
Labels: approved, lgtm, size/S

#2194 ci: stagger execution of CS periodics
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/L

#2192 k8s-config-connector: require self approval
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2201 Bump timeout for cit-periodics-performance
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2203 Bump individual workflow timeout to 60m for cit-periodics-performance
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2202 ci: further stagger each large GKE job
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2205 Update kubeflow-pipelines-presubmits.yaml to use go 1.21 for backend presubmit
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/XS

#2206 chore: Move configsync std clusters to us-central2
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2207 chore: configsync gke std clusters to us-west1
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2209 configsync: increase stress test node size
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2190 Run storage/networkperf and shapevalidation once per day on ubuntu devel images
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S
