Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-09, with the labels that each got.

#2365 Add oss-prow-builds cluster as default
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
Labels: approved, lgtm, size/XS

#2364 Add cron jobs to restart pcm/crier/sinker/deck every day
  prow/oss/cluster/crier-kicker.yaml
  prow/oss/cluster/deck-kicker.yaml
  prow/oss/cluster/prow-controller-manager-kicker.yaml
  prow/oss/cluster/sinker-kicker.yaml
Labels: approved, lgtm, size/L

#2369 chore: unpin autopilot rapid version
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2370 create new clusters for autopilot-rapid tests
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2362 chore: remove all-gcpc-modules-test prow config as it's being migrated to GHA
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#2353 Remove kubeflow-pipelines-integration-v2 from Prow Config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/S

#2371 chore: remove kfp postsubmits config
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
Labels: approved, lgtm, size/S

#2372 Remove osconfig staging unavailable zones
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#2374 Skip mds tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2373 Add galog presubmit checks
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/galog.yaml
Labels: approved, lgtm, size/M

#2376 Remove deb11-arm64 as it deprecated
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2375 Onboard GoogleCloudPlatform/galog to prow
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2377 bump timeout for config sync autopilot tests
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2378 Trigger TestGrid jobs on main, not master, branch.
  prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
Labels: approved, lgtm, size/S

#2380 Switch cit-periodics to include instead of exclude.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2382 Revert "create new clusters for autopilot-rapid tests"
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/S

#2383 Setup cherrypicker external-plugin for Kubeflow org.
  prow/oss/cluster/cherrypicker.yaml
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/M

#2385 Bind sinker to the same GSA as prow-controller-manager.
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/XS

#2384 Seperating cit-periodics to be per os
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/L

#2368 Split the OSS Prow and misc image autobumps.
  prow/oss/misc-images-autobump-config.yaml
  prow/oss/oss-prow-autobump-config.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/M

#2387 Address issues with cit-periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2386 Update gcp-guest-config.yaml
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2389 Don't expect misc images to be bumped consistently.
  prow/oss/misc-images-autobump-config.yaml
Labels: approved, lgtm, size/XS
