Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2024-04, with the labels that each got.

#2234 Bump cit-performance-peridiocs parallel count
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2235 Update CA Certificate for gcp-guest cluster
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/S

#2236 Specify namespace in update kubeconfig target
  prow/oss/Makefile
Labels: approved, lgtm, size/XS

#2237 Make postsubmit deploy job run on Makefile changes.
  prow/oss/cluster/prow-controller-manager.yaml
  prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Labels: approved, lgtm, size/XS

#2239 Fix gcp-guest CA cert and IP address.
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
Labels: approved, lgtm, size/S

#2242 Update compute-daisy presubmit config
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
Labels: approved, lgtm, size/M

#2243 Add autobump consistency exceptions for non-prow container images.
  prow/oss/oss-autobump-config.yaml
Labels: approved, lgtm, size/S

#2245 Disable tide on compute-daisy
  prow/oss/config.yaml
Labels: approved, lgtm, size/XS

#2246 Run all daisy status checks for every PR
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
Labels: approved, lgtm, size/S

#2248 Don't set exit status in cit-periodics and oslogin-periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2247 Trust copybara service to trigger tests
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2249 Revert changes to daisy presubmits
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
Labels: approved, lgtm, size/M

#2251 Removed `hold` plugin in Config Sync repository
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2253 remove listx from OWNERS
  .prow/OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#2256 Change prow command for k8s-cloud-providers
  prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml
Labels: approved, lgtm, size/XS

#2262 Modify the test related to python3.7
  prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Labels: approved, lgtm, size/M, needs-ok-to-test
