Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2025-02, with the labels that each got.

#2429 Rename kubeflow/training-operator to kubeflow/trainer
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#2432 Update create-build-cluster.sh
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#2433 Add credentials for build-kubeflow
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#2435 Add credentials for espv2-prow-build
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
Labels: approved, lgtm, size/XS

#2436 Correct the espv2 cluster name
  prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
Labels: approved, lgtm, size/XS

#2437 Add external secret from build cluster for openshift-eng
  prow/oss/cluster/kubernetes_external_secrets.yaml
  prow/oss/gencred-config/gencred-config.yaml
Labels: approved, lgtm, size/S

#2438 Add build cluster kubeconfig for openshift-eng
  prow/oss/cluster/crier.yaml
  prow/oss/cluster/deck.yaml
  prow/oss/cluster/deck_blueprints_deployment.yaml
  prow/oss/cluster/hook.yaml
  prow/oss/cluster/prow-controller-manager.yaml
  prow/oss/cluster/sinker.yaml
Labels: approved, lgtm, size/M

#2439 Modernize create-build-cluster.sh to use gke-auth-plugin kubeconfigs rather than gencred+KES.
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/L

#2441 Fix broken links to old Prow source location.
  README.md
  prow/oss/README.md
  prow/oss/onboarding.md
Labels: approved, lgtm, size/S

#2440 Fix create-build-cluster.sh Prow SA binding to test cluster.
  prow/oss/create-build-cluster.sh
Labels: approved, lgtm, size/XS

#2442 Add the machine shape argument to accelerator tests
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2443 Pass in europe-west1-b as the zone for a3u accelerator periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2444 Pass in the accelerator type
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2445 Adding ROS Cluster for Enterprise Workloads Testing
  prow/prowjobs/openshift/OWNERS
  prow/prowjobs/openshift/origin/openshift-origin-base-test.yaml
  testgrid/config.yaml
Labels: approved, lgtm, size/S

#2446 Use the correct reservation for a3u
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS
