Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2025-09, with the labels that each got.

#2528 Add free edition test to oracle-toolkit-presubmit.yaml
  prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Labels: approved, lgtm, size/S

#2529 Update OWNERS
  prow/prowjobs/google/oracle-toolkit/OWNERS
Labels: approved, lgtm, size/XS

#2527 Bump concurrency for rocky dev tests to 10
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2534 feat: Add v0.2 milestone for Kubeflow SDK
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#2535 Set required env vars for gcenode
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS
