Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2025-03, with the labels that each got.

#2448 Stop LGTM acting as approve in Kubeflow
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/S, ok-to-test

#2449 kpt-config-sync: more nodes for stress tests
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2450 Add A4 to CIT accelerator periodics
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2453 chore: update owners for Config Sync repository
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/OWNERS
Labels: approved, lgtm, size/XS

#2452 chore: bump kubekins-e2e for Config Sync jobs
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/S

#2456 kpt-config-sync: increase stress test memory
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2457 kpt-config-sync: more stress test nodes
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS
