Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2025-06, with the labels that each got.

#2488 Update cleanerupper timeout to 1h45m
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS

#2489 Update OWNERS file
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
Labels: approved, lgtm, size/XS

#2492 Remove ansible linter from oracle-toolkit
  prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Labels: approved, lgtm, size/S

#2493 chore: bump kubekins-e2e for config sync e2e
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/S

#2494 Remove ubuntu-2004 from testgrid, they're EOL
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2490 Update cleanerupper prow jobs to be more scoped down
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/L
