Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2025-10, with the labels that each got.

#2537 Update periodic images
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/M

#2538 Move arm tests to c4a
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/S

#2539 Increase test timeout for CIT A3U and A4 rdma tests.
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
