Repository GoogleCloudPlatform/oss-test-infra, pull requests merged in 2025-05, with the labels that each got.

#2474 Update Config Sync release branch CI to v1.21
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
Labels: approved, lgtm, size/XS

#2476 Enable Workload Identity for ansible-runner Pod
  prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Labels: approved, lgtm, size/XS

#2479 Add a test case for single-instance setup on BMS
  prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Labels: approved, lgtm, size/M

#2480 Use different SSH keys for RAC and single-instance setup
  prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Labels: approved, lgtm, size/S

#2481 Update GKE E2E test image version to v2.0.0-go1.24.3-gcloud513...
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
Labels: approved, lgtm, size/XS

#2482 Update reservation in a4 prow grid
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Labels: approved, lgtm, size/XS

#2483 ci: skip config sync e2e when only .github changes
  prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
Labels: approved, lgtm, size/XS

#2484 add hold plugin to kpt-config-sync
  prow/oss/plugins.yaml
Labels: approved, lgtm, size/XS

#2486 Update cadence and timeout for cleanerupper
  prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
Labels: approved, lgtm, size/XS
